# .streamlit/secrets.toml.example
[github]
token = "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"
repo_name = "idk_questionandsol"

gemini_api_key = "AIzaSyDNXbA5QJmxqiYFT8YF-iEFr5gl7MdPEZk"
openai_api_key = "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"
